version: '3.5'
services:
  base_db:
    image: mysql:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_DATABASE: dba_base
      MYSQL_USER: base
      MYSQL_PASSWORD: base
      MYSQL_ROOT_PASSWORD: base
    volumes:
      - ./data_mysql:/var/lib/mysql
  base_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_django_dir
    ports:
      - "8001:8000"
    depends_on:
      - base_db
